### ISSUE TITLE
Support for document-less graphs

### ISSUE THREAD

**Issue by mforkel** [tintinweb/vscode-interactive-graphviz#113]
I would like to display a dot graph that is created "on the fly" in my VSCode extension. The graph source is the output of `quilt graph`, there is no document. I tried

``` javascript
vscode.commands.executeCommand('graphviz-interactive-preview.preview.beside', { content: graph, title: patch.relativePath });
```
and got an error
```
stack trace: TypeError: Cannot read properties of undefined (reading 'uri')
	at /home/malte/.vscode-server/extensions/tintinweb.graphviz-interactive-preview-0.3.0/dist/extension.js:2:701553
	at new Promise (<anonymous>)
	at n.default.revealOrCreatePreview (/home/malte/.vscode-server/extensions/tintinweb.graphviz-interactive-preview-0.3.0/dist/extension.js:2:701504)
	at /home/malte/.vscode-server/extensions/tintinweb.graphviz-interactive-preview-0.3.0/dist/extension.js:2:787847
	at o._executeContributedCommand (/home/malte/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:62521)
	at o._doExecuteCommand (/home/malte/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:61341)
	at o.executeCommand (/home/malte/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:61247)
	at Object.executeCommand (/home/malte/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:97:31811)
	at SeriesProvider.graphPatch (/home/malte/dev/vsc-extension-quilt-lens/quilt-lens/out/series-explorer.js:163:29)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async o._executeContributedCommand (/home/malte/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:62513)
```

The value of `graph` is
``` dot
digraph dependencies {
    n4 [style=bold,color=grey,label="minmax.patch"];
}
```

It seems, a document is required in the options argument of the command.

Is there a way to render a document-less graph with your extension? If not, would you consider adding a command or an API for this use case?

**Comment by bigbug** [comment]
In PR 114 I switched the system from basically document identifying to URI identifying. I also allowed undefined URIs to appear. This should enable your use case. However you are losing the ability to update the preview if no URI is specified. Please be aware of that. I also updated the API to include a URI as a parameter. Please see updated README in the PR.

@mforkel Please verify whether this works for you and is suitable.
